[2024-01-28 09:31:23] [INFO    ] discord.client: logging in using static token
[2024-01-28 09:31:24] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 22889dff604101b9969d2f3844545973).
[2024-01-28 09:31:26] [INFO    ] discord: We have logged in as Sesshomaru#7078
[2024-01-28 09:31:26] [INFO    ] discord: Poll Setup
[2024-01-28 09:31:46] [INFO    ] discord: Poll command called
[2024-01-28 09:33:38] [INFO    ] discord: Poll command called
[2024-01-28 09:34:56] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command poll
Traceback (most recent call last):
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1021, in invoke
    await self.prepare(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 938, in prepare
    await self._parse_arguments(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 860, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 711, in transform
    raise exc
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 705, in transform
    ctx.current_argument = argument = view.get_quoted_word()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/view.py", line 184, in get_quoted_word
    raise InvalidEndOfQuotedStringError(next_char)  # type: ignore # this will always be a string
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discord.ext.commands.errors.InvalidEndOfQuotedStringError: Expected space after closing quotation but received 'I'
[2024-01-28 09:36:36] [INFO    ] discord: Poll command called
[2024-01-28 09:39:36] [INFO    ] discord: Poll command called
[2024-01-28 09:40:53] [INFO    ] discord: Poll command called
[2024-01-28 09:42:35] [INFO    ] discord: Poll command called
[2024-01-28 09:43:40] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command poll
Traceback (most recent call last):
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1021, in invoke
    await self.prepare(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 938, in prepare
    await self._parse_arguments(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 845, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 711, in transform
    raise exc
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 705, in transform
    ctx.current_argument = argument = view.get_quoted_word()
                                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/view.py", line 151, in get_quoted_word
    raise ExpectedClosingQuoteError(close_quote)
discord.ext.commands.errors.ExpectedClosingQuoteError: Expected closing ".
[2024-01-28 09:44:03] [INFO    ] discord: Poll command called
[2024-01-28 09:44:22] [INFO    ] discord: Poll command called
[2024-01-28 09:46:20] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command poll
Traceback (most recent call last):
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1021, in invoke
    await self.prepare(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 938, in prepare
    await self._parse_arguments(ctx)
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 845, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vile/repos/Sesshomaru/venv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 697, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: question is a required argument that is missing.
[2024-01-28 09:46:33] [INFO    ] discord: Poll command called
